services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: apps/docker/backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/apps/frontend/node_modules
      - ./dist:/apps/frontend/dist # Serve build output to nginx
    env_file:
      - ./.env
    restart: always

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/apps/backend/static
      - ./dist:/apps/frontend/dist # Serve frontend build from here
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  db-data:
  node_modules:
  static:
