FROM python:3.13.3-slim-bookworm@sha256:56a11364ffe0fee3bd60af6d6d5209eba8a99c2c16dc4c7c5861dc06261503cc

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"

# Install system dependencies for PostgreSQL, LDAP, and SASL
RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y --no-install-recommends \
  build-essential \
  libpq-dev \ 
  libldap2-dev \
  libsasl2-dev \
  redis-tools \
  gcc \
  slapd \
  ldap-utils \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set up a non-root user
RUN useradd -U app_user && \
    install -d -m 0755 -o app_user -g app_user /app

# Set working directory
WORKDIR /app

# Copy the requirements file 
COPY requirements.txt /tmp/requirements.txt

# Update pip
RUN pip install --upgrade pip

# Install dependencies
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm -rf /tmp/requirements.txt

# Copy project files and set permissions
COPY --chown=app_user:app_user . .

# Ensure shell scripts are executable
RUN chmod a+x docker/django/entrypoint.sh docker/django/start.sh

# For GitHub CI
RUN mkdir -p /app/.pytest_cache && chmod -R 777 /app/.pytest_cache

# Switch to non-root user
USER app_user:app_user

# Ensure media directory exists and is owned by app_user
RUN mkdir -p /app/media && chown -R app_user:app_user /app/media

# Set entrypoint
ENTRYPOINT [ "docker/django/entrypoint.sh" ]
CMD [ "docker/django/start.sh", "backend" ]
