# Generated by Django 5.2.5 on 2025-08-23 06:39

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apsts_creators', related_query_name='apsts_creators', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apsts_modifiers', related_query_name='apsts_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Approval Statuses',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dim_creator', related_query_name='dim_creator', to=settings.AUTH_USER_MODEL)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dim_lead', related_query_name='dim_lead', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dim_modifier', related_query_name='dim_modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('unit_of_measure', models.TextField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('previous_target', models.DecimalField(decimal_places=3, max_digits=4)),
                ('current_target', models.DecimalField(decimal_places=3, max_digits=4)),
                ('cumulative_target', models.DecimalField(decimal_places=3, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='init_creators', related_query_name='init_creators', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='init_modifiers', related_query_name='init_modifiers', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='init_sts', related_query_name='init_sts', to='posts.approvalstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_apvs', related_query_name='app_apvs', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_reqs', related_query_name='app_reqs', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_statuses', related_query_name='app_statuses', to='posts.approvalstatus')),
                ('approval_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appent_inits', related_query_name='appent_inits', to='posts.initiative')),
            ],
            options={
                'verbose_name_plural': 'Approval Entries',
            },
        ),
        migrations.CreateModel(
            name='InitiativeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cummulative_actual', models.DecimalField(decimal_places=3, max_digits=4)),
                ('action_description', models.TextField()),
                ('action_factor', models.TextField()),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weighted_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weighted_achieved', models.DecimalField(decimal_places=2, max_digits=4)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('in_progress', 'In Progress'), ('exceeding_target', 'Exceeding Target'), ('behind_schedule', 'Behind Schedule'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.CharField(help_text='Target deadline (e.g., Q4 2024)', max_length=100)),
                ('evidence', models.FileField(blank=True, help_text='Upload Word, PDF, JPEG, or PNG files.', null=True, upload_to='attachments/', validators=[posts.models.validate_file_extension])),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.initiative')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obj_creators', related_query_name='obj_creators', to=settings.AUTH_USER_MODEL)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obj_dims', related_query_name='obj_dims', to='posts.dimension')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obj_modifiers', related_query_name='obj_modifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.strategicobjective'),
        ),
    ]
