# Generated by Django 5.2.1 on 2025-07-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='annual_target',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='criteria',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='cummulative_actual',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='cummulative_target',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='factors_contributing',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='raw_score',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='statistical_explanation',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='status_of_activities',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='status_yr_2024',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='unit_of_measure',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='wtd_achievement',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='wtd_score',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
