# Generated by Django 5.2.1 on 2025-07-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_department_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='posts.division'),
        ),
    ]
