# Generated by Django 5.2.1 on 2025-07-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_criteria_alter_post_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='department',
        ),
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.branch'),
        ),
    ]
