# Generated by Django 5.2.1 on 2025-07-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_department_post_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload Word, PDF, JPEG, or PNG files.', null=True, upload_to='attachments/'),
        ),
    ]
