# Generated by Django 5.2.1 on 2025-07-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('priority', 'Priority Action'), ('achievement', 'Recent Achievement')], default='priority', max_length=20)),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_name', models.CharField(help_text='Icon name for frontend', max_length=100)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='posts.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=100)),
                ('trend', models.CharField(help_text='e.g., +5%, -2%', max_length=50)),
                ('icon_name', models.CharField(help_text='Icon name for frontend', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_metrics', to='posts.branch')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('in_progress', 'In Progress'), ('exceeding_target', 'Exceeding Target'), ('behind_schedule', 'Behind Schedule'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('target', models.CharField(help_text='Target description', max_length=255)),
                ('deadline', models.CharField(help_text='Target deadline (e.g., Q4 2024)', max_length=100)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_objectives', to='posts.branch')),
            ],
            options={
                'ordering': ['-priority', '-progress'],
            },
        ),
    ]
