# Generated by Django 5.2.1 on 2025-08-12 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_actionitem_keymetric_strategicobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When true, editing is disabled until unlocked by an administrator.'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='criteria_count',
            field=models.IntegerField(default=0, help_text='Number of criteria under this objective'),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='objectives_count',
            field=models.IntegerField(default=0, help_text='Number of sub-objectives under this objective'),
        ),
        migrations.CreateModel(
            name='StrategicCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Weight percentage', max_digits=5)),
                ('target_value', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_value', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategic_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='posts.strategicobjective')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
