# Generated by Django 5.2.1 on 2025-08-12 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_is_locked_post_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('annual_target', models.CharField(default='N/A', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='posts.branch')),
                ('criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='posts.criteria')),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='posts.subtitle')),
            ],
            options={
                'unique_together': {('branch', 'subtitle', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('target_quarter', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_quarter', models.CharField(blank=True, max_length=100, null=True)),
                ('cumulative_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('contributing_factors', models.TextField(blank=True, null=True)),
                ('raw_score', models.CharField(blank=True, max_length=50, null=True)),
                ('wtd_score', models.CharField(blank=True, max_length=50, null=True)),
                ('wtd_achievement', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='posts.performanceobjective')),
            ],
            options={
                'ordering': ['objective', 'year', 'quarter'],
                'unique_together': {('objective', 'year', 'quarter')},
            },
        ),
    ]
