# Generated by Django 5.2.1 on 2025-08-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_performanceobjective_rejection_comment'),
        ('posts', '0015_objective_index'),
    ]

    operations = [
    ]
