# Generated by Django 5.2.5 on 2025-08-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceobjective',
            name='unit_of_measure_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
